#!/usr/bin/env python3
"""
PT/INR Computation Module for Blood Coagulation Analysis

This module computes Prothrombin Time (PT) and International Normalized Ratio (INR)
from motion curve data generated by video analysis.

Direct port from MATLAB: compute_pt.m

Medical Device Modernization - Phase 1b
⚠️ CRITICAL: Life-critical medical calculation - EXACT algorithm port
NO modifications, NO optimizations

Formula: INR = (PT_patient / PT_normal)^(ISI - ALPHA)
"""

import argparse
import logging
import sys
from pathlib import Path
from typing import Tuple

import numpy as np
from scipy.signal import find_peaks
from scipy.ndimage import uniform_filter1d

from motion_analysis import find_knee_point


# ============================================================================
# CRITICAL MEDICAL CONSTANTS - DO NOT MODIFY
# ============================================================================
# These values are validated against published medical literature
# and clinical standards for PT/INR calculation

PT_NORMAL = 12.0      # Normal prothrombin time (seconds)
ISI = 1.31            # International Sensitivity Index
ALPHA = -0.31         # Correction factor
FPS = 60              # Video frame rate (frames per second)
FRAME_INTERVAL = FPS / 10  # Frame sampling interval

# ============================================================================


def movmean(data: np.ndarray, window: int) -> np.ndarray:
    """
    Moving average filter (MATLAB movmean equivalent).

    Args:
        data: Input 1D array
        window: Window size for averaging

    Returns:
        Smoothed array (same length as input)
    """
    return uniform_filter1d(data, size=window, mode='nearest')


def compute_pt_inr(
    start_time_file: str,
    stop_time_file: str,
    fps: float = FPS,
    verbose: bool = False
) -> Tuple[float, float, dict]:
    """
    Compute PT and INR from motion curve files.

    Direct port of compute_pt.m (MATLAB).

    Args:
        start_time_file: Path to pipette motion curve file
        stop_time_file: Path to particle motion curve file
        fps: Video frame rate (default: 60)
        verbose: Enable detailed logging

    Returns:
        Tuple of (PT, INR, debug_info)
        - PT: Prothrombin Time in seconds
        - INR: International Normalized Ratio
        - debug_info: Dictionary with intermediate values for validation

    Raises:
        FileNotFoundError: If motion curve files not found
        ValueError: If computation fails

    Algorithm (from MATLAB):
        1. Read and smooth motion curves
        2. Find start time (pipette motion onset):
           - Find knee point of pipette curve
           - Crop to knee point
           - Find most prominent peak → start time
        3. Find end time (particle cessation):
           - Offset by 10 seconds from start
           - Normalize curve [0,1]
           - Find knee point → end time
        4. Calculate PT = end_time - start_time
        5. Calculate INR = (PT / PT_normal)^(ISI - ALPHA)
    """
    logger = logging.getLogger(__name__)

    # Read motion curves
    logger.info(f"Reading motion curves...")
    logger.info(f"  Start time file: {start_time_file}")
    logger.info(f"  Stop time file: {stop_time_file}")

    begin_video = np.loadtxt(start_time_file, delimiter=',')
    end_video = np.loadtxt(stop_time_file, delimiter=',')

    logger.info(f"  Begin video points: {len(begin_video)}")
    logger.info(f"  End video points: {len(end_video)}")

    # Smooth particle motion curve (MATLAB: movmean(end_video,10))
    end_video = movmean(end_video, 10)

    # Create time vector
    # MATLAB: t=linspace(0,(length(end_video)*(fps/10))/fps,sz(2))
    t = np.linspace(0, (len(end_video) * (fps / 10)) / fps, len(end_video))

    logger.info(f"Time vector: 0 to {t[-1]:.2f}s, {len(t)} points")

    # ========================================================================
    # CALCULATE START TIME (pipette motion onset)
    # ========================================================================
    logger.info("\nCalculating start time (pipette motion onset)...")

    # Smooth pipette curve
    begin_video_smooth = movmean(begin_video, 10)

    # Find knee point
    kp_x, kp = find_knee_point(begin_video_smooth)
    logger.info(f"  Knee point at index: {kp}")

    # Crop to knee point
    begin_video = begin_video[:kp + 1]  # +1 to include knee point (MATLAB 1-indexed)
    xstart = np.linspace(0, (len(begin_video) * (fps / 10)) / fps, len(begin_video))

    logger.info(f"  Cropped to {len(begin_video)} points")

    # Find most prominent peak
    # MATLAB: [pks,locs,~,p]=findpeaks(begin_video)
    # In scipy, prominence is calculated separately
    peaks, properties = find_peaks(begin_video, prominence=0)

    if len(peaks) == 0:
        raise ValueError("No peaks found in start time curve")

    prominences = properties['prominences']
    logger.info(f"  Found {len(peaks)} peaks")

    # Find peak with maximum prominence
    startp = np.argmax(prominences)
    startloc = peaks[startp]
    begin_time = t[startloc]

    logger.info(f"  Most prominent peak at index: {startloc}")
    logger.info(f"  Start time: {begin_time:.3f}s")

    # ========================================================================
    # CALCULATE END TIME (particle cessation)
    # ========================================================================
    logger.info("\nCalculating end time (particle cessation)...")

    # Offset by 10 seconds from start
    # MATLAB: offset=startloc+(10*10)
    offset = startloc + (10 * 10)  # 10 seconds * 10 samples/second
    logger.info(f"  Offset: {offset} samples")

    end_video = end_video[offset:]
    logger.info(f"  After offset: {len(end_video)} points")

    # Normalize curve [0,1]
    # MATLAB: end_video=(end_video-min(end_video))/(max(end_video)-min(end_video))
    end_video = (end_video - np.min(end_video)) / (np.max(end_video) - np.min(end_video))
    logger.info(f"  Normalized: min={np.min(end_video):.3f}, max={np.max(end_video):.3f}")

    # Trim off end where motion < 0.01
    # MATLAB: f=find(end_video<.01); end_video=end_video(1:f(1))
    f = np.where(end_video < 0.01)[0]
    if len(f) > 0:
        end_video = end_video[:f[0] + 1]  # +1 to include the point
        logger.info(f"  Trimmed at threshold 0.01: {len(end_video)} points remaining")

    # Find knee point of normalized curve
    kp_x2, kp2 = find_knee_point(end_video)
    kp_final = kp2 + offset  # Add back the offset
    end_time = t[kp_final]

    logger.info(f"  Knee point at index: {kp2} (offset: {kp_final})")
    logger.info(f"  End time: {end_time:.3f}s")

    # ========================================================================
    # CALCULATE PT AND INR
    # ========================================================================
    logger.info("\nCalculating PT and INR...")

    pt = end_time - begin_time
    logger.info(f"  PT = end_time - begin_time")
    logger.info(f"  PT = {end_time:.3f} - {begin_time:.3f}")
    logger.info(f"  PT = {pt:.3f} seconds")

    # INR formula: (PT / PT_normal)^(ISI - ALPHA)
    # MATLAB: inr=(pt/pt_normal).^(isi-alpha)
    exponent = ISI - ALPHA
    inr = (pt / PT_NORMAL) ** exponent

    logger.info(f"\n  INR = (PT / PT_normal)^(ISI - ALPHA)")
    logger.info(f"  INR = ({pt:.3f} / {PT_NORMAL}) ^ ({ISI} - ({ALPHA}))")
    logger.info(f"  INR = ({pt / PT_NORMAL:.6f}) ^ {exponent}")
    logger.info(f"  INR = {inr:.6f}")

    # Compile debug info for validation
    debug_info = {
        'begin_time': begin_time,
        'end_time': end_time,
        'start_loc': startloc,
        'offset': offset,
        'kp_final': kp_final,
        'pt_normal': PT_NORMAL,
        'isi': ISI,
        'alpha': ALPHA,
        'exponent': exponent
    }

    return pt, inr, debug_info


def main() -> int:
    """Main entry point for PT/INR computation."""
    parser = argparse.ArgumentParser(
        description='Compute PT and INR from motion curve files',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s                                    # Use default files
  %(prog)s -s start.txt -e stop.txt          # Custom files
  %(prog)s -v                                # Verbose output

Medical Device Modernization - Phase 1b
CRITICAL: Life-critical medical calculation
        """
    )

    parser.add_argument(
        '-s', '--start-file',
        default='start_time_video.txt',
        help='Start time motion curve file (default: start_time_video.txt)'
    )

    parser.add_argument(
        '-e', '--stop-file',
        default='stop_time_video.txt',
        help='Stop time motion curve file (default: stop_time_video.txt)'
    )

    parser.add_argument(
        '--fps',
        type=float,
        default=FPS,
        help=f'Video frame rate (default: {FPS})'
    )

    parser.add_argument(
        '-v', '--verbose',
        action='store_true',
        help='Enable verbose logging'
    )

    parser.add_argument(
        '--version',
        action='version',
        version='%(prog)s 2.0.0 (Phase 1b)'
    )

    args = parser.parse_args()

    # Setup logging
    log_level = logging.DEBUG if args.verbose else logging.INFO
    logging.basicConfig(
        level=log_level,
        format='%(levelname)s: %(message)s'
    )

    logger = logging.getLogger(__name__)

    try:
        # Check files exist
        if not Path(args.start_file).exists():
            logger.error(f"Start file not found: {args.start_file}")
            return 1

        if not Path(args.stop_file).exists():
            logger.error(f"Stop file not found: {args.stop_file}")
            return 1

        # Compute PT/INR
        logger.info("=" * 60)
        logger.info("PT/INR COMPUTATION - Medical Device Phase 1b")
        logger.info("=" * 60)

        pt, inr, debug_info = compute_pt_inr(
            args.start_file,
            args.stop_file,
            fps=args.fps,
            verbose=args.verbose
        )

        # Output results (MATLAB format)
        logger.info("\n" + "=" * 60)
        logger.info("RESULTS")
        logger.info("=" * 60)
        print(f"PT: {pt:.1f}")
        print(f"INR: {inr:.1f}")
        logger.info("=" * 60)

        return 0

    except Exception as e:
        logger.error(f"Computation failed: {e}")
        if args.verbose:
            import traceback
            traceback.print_exc()
        return 1


if __name__ == '__main__':
    sys.exit(main())
